trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: AutomatedTestsJob
    timeoutInMinutes: 720
    steps:
      - task: Bash@3
        displayName: 'Set Single Test XML File'
        inputs:
          targetType: 'inline'
          script: |
            echo "Running a single test suite manually."
            echo "##vso[task.setvariable variable=SINGLE_TEST_XML_FILE]src/test/TestNGXMLSuites/SingleTestRun.xml"

      - task: Bash@3
        displayName: 'Create .env file'
        inputs:
          targetType: 'inline'
          script: |
            echo "PIPELINE_RUN=$PIPELINE_RUN" >> seleniumTest/.env
            cat seleniumTest/.env

      - task: Maven@3
        displayName: 'Run Single Test Suite'
        inputs:
          mavenPomFile: 'seleniumTest/pom.xml'
          mavenOptions: '-Xmx3072m'
          goals: 'test'
          options: '-Dsurefire.suiteXmlFiles=$(SINGLE_TEST_XML_FILE)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '11'
          mavenVersionOption: 'Default'
          targetPath: '$(System.DefaultWorkingDirectory)/seleniumTest/target/surefire-reports'
          artifact: 'SurefireReports'
